### ISSUE TITLE
AttributeError: 'PluginServicesProxy' object has no attribute 'add'

### ISSUE THREAD

**Issue by tvmvmaor** [kaltura/clients-generator#508]
Running a python-script on a Debian 9 server. Have tested on several servers. Also tested on MacOS. Same result.

I keep getting this error:

```
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    result = client.bulkUpload.add(conversion_profile_id, csv_file_data, bulk_upload_type, uploaded_by, file_name)
AttributeError: 'PluginServicesProxy' object has no attribute 'add'
```

- Python 3.8.1 (it works on some Python 2.7 installs - others not)
- pip install KalturaApiClient (connecting to Kaltura SaaS)
- Funny thing is: It _always_ works when using **sudo** eg. "sudo python test.py"
- Python is installed correctly and all other Kaltura API functionality seems to be working.

```
from KalturaClient import *
from KalturaClient.Plugins.Core import *

config = KalturaConfiguration()
config.serviceUrl = "https://www.kaltura.com/"
client = KalturaClient(config)
ks = client.session.start(
      "",
      "",
      KalturaSessionType.ADMIN,
     )
client.setKs(ks)

conversion_profile_id = -1
csv_file_data = open('tvmidtvest-16621f84-d85c-4e9a-a420-76c6eb3a7b7e.xml', 'rb')
bulk_upload_type = KalturaBulkUploadType.XML
uploaded_by = ""
file_name = "tvmidtvest-16621f84-d85c-4e9a-a420-76c6eb3a7b7e.xml"

result = client.bulkUpload.add(conversion_profile_id, csv_file_data, bulk_upload_type, uploaded_by, file_name)
print(result)
```

**Comment by kaltura-hooks** [comment]
Hi @tvmvmaor,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by jessp01** [comment]
Hello @tvmvmaor ,

The entire `bulkUpload` service is deprecated. Please use `media.bulkUploadAdd()`  instead (https://developer.kaltura.com/console/service/media/action/bulkUploadAdd?query=media).

Let me know if that works correctly (it should).

Thanks,

**Comment by tvmvmaor** [comment]
Hi @jessp01 

Thanks for getting back to me.

I keep getting an error running this example code (credentials removed):

```
from KalturaClient import *
from KalturaClient.Plugins.Core import *

config = KalturaConfiguration()
config.serviceUrl = "https://www.kaltura.com/"
client = KalturaClient(config)
ks = client.session.start(
      "",
      "",
      KalturaSessionType.ADMIN,
     )
client.setKs(ks)

file_name = "tvmidtvest-d472d2f9-a004-4ae1-8795-1885674a63d7.xml"

file_data = open(file_name, 'rb')

bulk_upload_data = KalturaBulkUploadXmlJobData()
bulk_upload_entry_data = KalturaBulkUploadEntryData()

result = client.media.bulkUploadAdd(file_data)

print(result)
```

Error:
```
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    bulk_upload_data = KalturaBulkUploadXmlJobData()
NameError: name 'KalturaBulkUploadXmlJobData' is not defined
```

It's almost exactly the same code as the output from https://developer.kaltura.com/console/service/media/action/bulkUploadAdd?query=media (credentials removed) (which works with the exact same xml-file (tvmidtvest-d472d2f9-a004-4ae1-8795-1885674a63d7.xml)) :

```
from KalturaClient import *
from KalturaClient.Plugins.Core import *

config = KalturaConfiguration()
config.serviceUrl = "https://www.kaltura.com/"
client = KalturaClient(config)
ks = client.session.start(
      "",
      "",
      KalturaSessionType.ADMIN,
     )
client.setKs(ks)

file_data = open('/path/to/file', 'rb')
bulk_upload_data = KalturaBulkUploadXmlJobData()
bulk_upload_entry_data = KalturaBulkUploadEntryData()

result = client.media.bulkUploadAdd(file_data)
print(result)
```
Server: Debian 9
Python: Python 3.8.1
Kaltura API Client: KalturaApiClient-15.14.0
